### ISSUE TITLE
Recursive inherit in index.theme

### ISSUE THREAD

**Issue by Consolatis** [robson-66/GANT#1]
https://github.com/robson-66/GANT/blob/f62881822391de72fef7b2372471b138271b8e83/index.theme#L1-L4

This causes issues when using the cursor theme with some xcursor loaders as can be seen here: https://gitlab.freedesktop.org/wayland/wayland/-/issues/317

See also: https://aur.archlinux.org/packages/gant-icon-theme#comment-964205

**Comment by robson-66** [comment]
It works fine for me, you can edit this file yourself.
